### ISSUE TITLE
Open `comma-dangle`

### ISSUE THREAD

**Issue by zyyv** [developer-plus/eslint-config#1]
我觉得开启 `comma-dangle` 比较好
e.g.
```ts
{
  name: 'xxx',
  age: 18 // 年龄
}
```

如果我们继续往这个对象后面追加属性，因此我需要在`age: 18`后面添加`,`，有一个移动光标寻找正确落点的过程，太繁琐了，而且还不能在行尾添加`,`，因为存在注释

-------
如果有`comma-dangle`
```ts
{
  name: 'xxx',
  age: 18, // 年龄
  ...
}
```
我们只需要在后面进行换行，继续追加属性就好了

**Comment by Hongbusi** [comment]
打开 `comma-dangle` 在追加的时候，确实可以更加方便。

但是为了美观，我们在 0.1.0 版本讨论了关于 `comma-dangle` 的开启关闭问题，最终统一决定关闭，并在 0.1.1 版本发布。
